name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          scandir: './scripts'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check JavaScript syntax
        run: |
          find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;

  # IF {{ENABLE_TESTS}}
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check coverage threshold
        run: |
          # Verify coverage meets 85% threshold
          npm run test:coverage
  # END IF

  # IF {{ENABLE_CODECOV}}
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage report
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
  # END IF

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '{{DEPLOY_FOLDER}}'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  quality-check:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify shell script standards
        run: |
          echo "Checking shell script standards..."
          
          # Check for running timer in all scripts
          for script in scripts/*.sh scripts/lib/*.sh; do
            if [ -f "$script" ]; then
              echo "Checking $script for timer implementation..."
              if ! grep -q "update_timer\|TIMER_PID" "$script" && ! grep -q "source.*common.sh" "$script"; then
                echo "ERROR: $script missing timer implementation"
                exit 1
              fi
              
              echo "Checking $script for help flag..."
              if ! grep -q "show_help\|-h\|--help" "$script"; then
                echo "ERROR: $script missing help flag"
                exit 1
              fi
              
              echo "Checking $script for verbose flag..."
              if ! grep -q "VERBOSE\|-v\|--verbose" "$script"; then
                echo "ERROR: $script missing verbose flag"
                exit 1
              fi
            fi
          done
          
          echo "✅ All shell scripts meet standards"

      - name: All quality gates passed
        run: echo "✅ All quality checks passed"

