name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          scandir: './scripts'
          ignore_paths: 'node_modules vendor'

  javascript:
    name: JavaScript Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check JavaScript syntax
        run: |
          find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;

  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
        continue-on-error: true

  html:
    name: HTML Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          # Basic HTML validation - check for DOCTYPE and closing tags
          for file in $(find . -name "*.html" -not -path "*/node_modules/*"); do
            echo "Checking $file"
            if ! grep -q "<!DOCTYPE html>" "$file"; then
              echo "ERROR: Missing DOCTYPE in $file"
              exit 1
            fi
            if ! grep -q "</html>" "$file"; then
              echo "ERROR: Missing closing </html> tag in $file"
              exit 1
            fi
          done
          echo "All HTML files validated successfully"

  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: [shellcheck, javascript, markdown, html]
    steps:
      - name: All checks passed
        run: echo "✅ All linting checks passed"

